Update guide-ch_budget.xml
Gnucash/gnucash-docs pull request #200
Opened 2021-07-21 16:09 UTC by usamimikamen-sk

Add markups for translation.

2021-07-23 16:51 UTC, usamimikamen-sk commented
According to the [Documentation Update Instructions](https://wiki.gnucash.org/wiki/Documentation_Update_Instructions#Text_conventions), I think it is better to use &minus;.

2021-07-23 17:20 UTC, jralls commented
It says 
> The typographically correct symbol to use is − (U+2212, &minus;). The ASCII hyphen-minus - (U+002d) is commonly used and ***is also fine***. Whichever you use, be consistent, at least on the whole page. [emphasis added]

I don't see any other uses of - or `&minus;` on that page so consistency isn't an issue here.

2021-07-24 03:57 UTC, usamimikamen-sk commented
&amp;minus; is already introduced some chapter like  https://github.com/Gnucash/gnucash-docs/blob/45ddec8919526557fbe7c8e02fb9c682180d84fd/guide/C/ch_invest.xml#L1666

So I think there is a plan to use it. And current documents will be modified in order to use it gradually. 

@fellen
Do you have a plan to use &amp;minus; instead of ASCII '-'?

2021-07-28 15:35 UTC, fellen commented
> &minus; is already introduced some chapter like
> 
> https://github.com/Gnucash/gnucash-docs/blob/45ddec8919526557fbe7c8e02fb9c682180d84fd/guide/C/ch_invest.xml#L1666
> 
> So I think there is a plan to use it. And current documents will be modified in order to use it gradually.
> 
> @fellen
> Do you have a plan to use &minus; instead of ASCII '-'?

guide/C/ch_invest.xml is the only place.
I have no strong opinion. As it an almost invisible change, I would set the priority to change it to low, but if you want typographical correctness before translation I will not hinder you.

2021-08-12 15:09 UTC, fellen requested changes
A few minor changes would be fine.
Also line 22:
It can help you to plan …

Also sections like `Creating a Budget` could become `<task>`s.

2021-08-19 16:53 UTC, usamimikamen-sk reviewed
[dtd-translate.patch.txt](https://github.com/Gnucash/gnucash-docs/files/7016300/dtd-translate.patch.txt)

I applied this patch, then create html and PDF.
But &lt;accel&gt; tag seems to do nothing.

How &lt;accel&gt; is shown in yelp?
In some cases, we need to cusomize xsl stylesheet files.

2021-08-21 02:02 UTC, usamimikamen-sk commented on guide/C/ch_budgets.xml
> +      <para>Now, you must enter the budget values&ndash;the amounts that you expect the account balances to change
6e5de97a

2021-08-21 02:04 UTC, usamimikamen-sk commented on guide/C/ch_budgets.xml
> +        <guimenu>Reports</guimenu><guisubmenu>Budget</guisubmenu> <guimenuitem>Budget Report</guimenuitem>
I'll do it after PR #207 will be accepted.

2021-08-21 02:41 UTC, usamimikamen-sk commented
> Also sections like `Creating a Budget` could become `<task>`s.
I tried to use <task> and <procedure> instead of <sect2> in 2a86e5d.
Does it match your image?

2021-08-24 16:08 UTC, usamimikamen-sk commented
> A few minor changes would be fine.
> Also line 22:
> It can help you to plan …

What do you mean? Is line 22 correct?
 
> Also sections like `Creating a Budget` could become `<task>`s.
Done.

2021-08-25 02:26 UTC, fellen commented
> How <accel> is shown in yelp?

![image](https://user-images.githubusercontent.com/6572538/130716208-5825b56a-1ab8-4d4f-94b1-879d7b686647.png)

2021-08-25 02:53 UTC, fellen commented
> Does it match your image?

Excellent!
But you could do more formalization by 

- converting  `<para>Before you begin…` into the taskprerequisites and
-  find parts belonging into tasksummary …

2021-08-25 03:04 UTC, fellen commented
> > It can help you to plan …
> 
> What do you mean? Is line 22 correct?

`You can use it to help you plan …` has some redundancy—3 verbs. So i suggested
`It can help you to plan …`

2021-08-25 05:10 UTC, usamimikamen-sk commented
> ![image](https://user-images.githubusercontent.com/6572538/130716208-5825b56a-1ab8-4d4f-94b1-879d7b686647.png)
Thank you.

TODO:
HTML/FO `<accel>` tag underline.
Create accel-{fo,html}.xsl to apply CSS to <accel> tag.

2023-03-27 18:09 UTC, closed without merging